apiVersion: batch/v1
kind: Job
metadata:
  name: memory-stress
  namespace: demo-app
spec:
  template:
    spec:
      containers:
        - name: stress
          image: polinux/stress
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          command: ["stress"]
          args: ["--vm", "1", "--vm-bytes", "400M", "--vm-hang", "0"]
      restartPolicy: Never
